name: Run Cluster Test

on:
  push:
    branches: [ main ]

jobs:
  start:
    name: cluster run
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup local bin path
        run: |
          mkdir -p "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Install deps
        run: |
          ./bin/deps
          echo $PATH
          which argocd

      - name: Create Cluster
        run: ./bin/setup

      - name: Validate Cluster
        run: ./bin/test
